version: '3'
services:
  app:
    env_file: .env
    build: .
    ports:
      - "5000:5000"
    environment:
      - AMADEUS_API_KEY=${AMADEUS_API_KEY}
      - AMADEUS_API_SECRET=${AMADEUS_API_SECRET}
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
